DROP DATABASE IF EXISTS db_usuario;

CREATE DATABASE db_usuario DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE PAIS
(CODIGO INT AUTO_INCREMENT,
NOMBRE VARCHAR(30) NOT NULL,
PRIMARY KEY (CODIGO));

CREATE TABLE OCUPACION
(CODIGO INT AUTO_INCREMENT,
NOMBRE VARCHAR(30) NOT NULL,
PRIMARY KEY (CODIGO));

CREATE TABLE ESTADO
(CODIGO INT AUTO_INCREMENT,
NOMBRE VARCHAR(30) NOT NULL,
CODIGO_PAIS INT(4) NOT NULL,
PRIMARY KEY (CODIGO),
FOREIGN KEY (CODIGO_PAIS) REFERENCES PAIS(CODIGO));

CREATE TABLE CIUDAD
(CODIGO INT AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
CODIGO_ESTADO INT(4) NOT NULL,
PRIMARY KEY (CODIGO),
FOREIGN KEY (CODIGO_ESTADO) REFERENCES ESTADO(CODIGO));

CREATE TABLE PERSONA 
(EMAIL VARCHAR(255) UNIQUE,
USUARIO VARCHAR(255) NOT NULL,
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(60),
CONTRASEÑA VARCHAR(255) NOT NULL,
PROFESOR BOOLEAN,
ADMINISTRADOR BOOLEAN,
FECHA_NAC DATE,
INTERES VARCHAR(255),
CODIGO_CIUDAD INT,
CODIGO_OCUP INT,
PRIMARY KEY (EMAIL),
FOREIGN KEY (CODIGO_CIUDAD) REFERENCES CIUDAD(CODIGO),
FOREIGN KEY (CODIGO_OCUP) REFERENCES OCUPACION(CODIGO));