INSERT INTO ocupacion(NOMBRE) VALUES ("ESTUDIANTE");
INSERT INTO ocupacion(NOMBRE) VALUES ("EMPLEADO");
INSERT INTO ocupacion(NOMBRE) VALUES ("INDEPENDIENTE");
INSERT INTO ocupacion(NOMBRE) VALUES ("OTRO");